In [3]:
import arviz as az
import numpy as np
import pandas as pd
import pymc as pm
from pymc.math import exp, ge, switch

In [4]:
data = pd.read_csv("bladderc.csv")

In [13]:
data.head(20)

time  observed  group
0      0         0      0
1      1         0      0
2      4         0      0
3      7         0      0
4     10         0      0
5      6         1      0
6     14         0      0
7     18         0      0
8      5         1      0
9     12         1      0
10    23         0      0
11    10         1      0
12     3         1      0
13     3         1      0
14     7         1      0
15     3         1      0
16    26         0      0
17     1         1      0
18     2         1      0
19    25         1      0

In [15]:
censored = data[data.observed==0]['observed'].values
y_uncensored = data[data.observed!=0]['time'].values
x_uncensored = data[data.observed!=0]['group'].values
x_censored = data[data.observed==0]['group'].values
censored

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [10]:
censored

array([ 0,  1,  4,  7, 10, 14, 18, 23, 26, 29, 29, 29, 32, 34, 36, 37, 41,
       49, 59,  1,  1,  9, 10, 13, 18, 22, 25, 25, 25, 38, 41, 41, 44, 45,
       46, 49, 50, 54, 59])

In [16]:
y_uncensored

array([ 6,  5, 12, 10,  3,  3,  7,  3,  1,  2, 25, 28,  2,  3, 12, 29,  9,
       16,  3,  6,  3,  9, 18, 35, 17,  3,  2,  5,  2,  5,  3,  1, 17,  2,
       17,  6,  6,  2, 26, 22,  4, 24,  1,  2,  2,  4, 38])

In [17]:
x_uncensored

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [9]:
x_uncensored

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [19]:
x_censored

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

So if we oberved the tumor, we want to right-censor the data. If not, we don't.

In [5]:
data["censored"] = 0
data.loc[data["observed"] == 0, "censored"] = data["time"]

y = data["time"].to_numpy(copy=True)
x = data["group"].to_numpy(copy=True)
observed = data["observed"].to_numpy(copy=True).astype(bool)
censored = data["censored"].to_numpy(copy=True)

np.sum(observed), y.shape, x.shape, observed.shape, censored.shape

(47, (86,), (86,), (86,), (86,))

In [6]:
x_uncensored = x[observed]
x_censored = x[~observed]

In [7]:
y_uncensored = y[observed]

In [8]:
censored = censored[~observed]

In [11]:
y_uncensored

array([ 6,  5, 12, 10,  3,  3,  7,  3,  1,  2, 25, 28,  2,  3, 12, 29,  9,
       16,  3,  6,  3,  9, 18, 35, 17,  3,  2,  5,  2,  5,  3,  1, 17,  2,
       17,  6,  6,  2, 26, 22,  4, 24,  1,  2,  2,  4, 38])

In [13]:
x_uncensored

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1])

In [23]:
# right-censored model

with pm.Model() as m:
    beta0 = pm.Normal("beta0", 0, sigma=1000)
    beta1 = pm.Normal("beta1", 0, sigma=1000)
    
    λ_uncensored = exp(beta0 + beta1 * x_uncensored)
    λ_censored = exp(beta0 + beta1 * x_censored)
    
    likelihood_uncensored = pm.Exponential("likelihood_uncensored", λ_uncensored, observed=y_uncensored, shape=y_uncensored.shape[0])
    likelihood_censored = pm.Bound("censored", pm.Exponential.dist(λ_censored), lower=censored, upper=np.inf, shape=censored.shape[0])

    mu_placebo = pm.Deterministic("mu_placebo", exp(-beta0))
    mu_chemo = pm.Deterministic("mu_chemo", exp(-beta0 - beta1))

    mu_diff = pm.Deterministic("mu_diff", mu_chemo - mu_placebo)

    H_prob = pm.Deterministic("H_prob", switch(ge(mu_diff, 0), 1, 0))

    H_prob2 = pm.Deterministic("H_prob2", switch(ge(mu_chemo, mu_placebo), 1, 0))
    trace = pm.sample(
        10000, tune=2000, cores=4, init="auto"
    )

/Users/aaron/mambaforge/envs/pymc-dev-py39/lib/python3.9/site-packages/aesara/tensor/elemwise.py:768: RuntimeWarning: overflow encountered in exp
  variables = ufunc(*ufunc_args, **ufunc_kwargs)
/Users/aaron/mambaforge/envs/pymc-dev-py39/lib/python3.9/site-packages/pymc/sampling.py:635: UserWarning: Unable to validate shapes: Cannot sample from a bounded variable
Apply node that caused the error: bound_rv{0, (0, 0, 0), floatX, False}(RandomStateSharedVariable(<RandomState(MT19937) at 0x1665FFD40>), TensorConstant{(1,) of 39}, TensorConstant{11}, exponential_rv{0, (0,), floatX, False}.out, TensorConstant{[ 0.  1.  ... 54. 59.]}, TensorConstant{inf})
Toposort index: 13
Inputs types: [RandomStateType, TensorType(int64, (1,)), TensorType(int64, ()), TensorType(float64, (None,)), TensorType(float64, (39,)), TensorType(float64, ())]
Inputs shapes: ['No shapes', (1,), (), (39,), (39,), ()]
Inputs strides: ['No strides', (8,), (), (8,), (8,), ()]
Inputs values: [RandomState(MT19937) at 0x1665F

/Users/aaron/mambaforge/envs/pymc-dev-py39/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:624: RuntimeWarning: overflow encountered in _beta_ppf
  return _boost._beta_ppf(q, a, b)
/Users/aaron/mambaforge/envs/pymc-dev-py39/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:624: RuntimeWarning: overflow encountered in _beta_ppf
  return _boost._beta_ppf(q, a, b)
/Users/aaron/mambaforge/envs/pymc-dev-py39/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:624: RuntimeWarning: overflow encountered in _beta_ppf
  return _boost._beta_ppf(q, a, b)
/Users/aaron/mambaforge/envs/pymc-dev-py39/lib/python3.9/site-packages/scipy/stats/_continuous_distns.py:624: RuntimeWarning: overflow encountered in _beta_ppf
  return _boost._beta_ppf(q, a, b)
Sampling 4 chains for 2_000 tune and 10_000 draw iterations (8_000 + 40_000 draws total) took 21 seconds.


In [22]:
az.summary(trace, hdi_prob=0.9)

mean      sd  hdi_5%  hdi_95%  mcse_mean  mcse_sd  ess_bulk  \
beta0          -3.280   0.186  -3.588   -2.975      0.001    0.001   19211.0   
beta1          -0.540   0.303  -1.022   -0.029      0.002    0.002   18118.0   
censored[0]    27.136  27.624   0.001   62.629      0.146    0.104   23322.0   
censored[1]    28.127  27.965   1.000   63.868      0.132    0.103   31817.0   
censored[2]    31.161  28.345   4.000   67.208      0.139    0.103   27466.0   
censored[3]    34.126  28.021   7.000   70.057      0.145    0.103   24576.0   
censored[4]    37.096  28.078  10.000   72.813      0.138    0.105   29287.0   
censored[5]    41.177  28.141  14.002   77.106      0.142    0.104   25344.0   
censored[6]    45.021  28.273  18.001   80.648      0.136    0.105   30355.0   
censored[7]    50.218  28.304  23.000   86.367      0.140    0.102   26083.0   
censored[8]    52.990  28.059  26.003   88.413      0.148    0.104   22842.0   
censored[9]    56.145  28.043  29.000   91.801      0.138    0.101   28002.0   
censored[10]   56.096  27.696  29.003   91.186      0.146    0.103   23142.0   
censored[11]   56.184  28.266  29.000   92.202      0.138    0.099   25342.0   
censored[12]   59.027  28.064  32.001   94.677      0.142    0.100   24653.0   
censored[13]   61.135  28.137  34.000   96.938      0.133    0.100   30223.0   
censored[14]   63.235  28.346  36.001   99.045      0.142    0.102   24963.0   
censored[15]   63.939  27.811  37.002   99.014      0.136    0.098   27096.0   
censored[16]   68.230  28.169  41.001  104.629      0.141    0.100   25984.0   
censored[17]   76.023  27.942  49.001  111.748      0.137    0.098   25944.0   
censored[18]   86.218  28.145  59.000  122.071      0.136    0.100   27653.0   
censored[19]   48.164  49.529   1.004  111.339      0.245    0.183   28252.0   
censored[20]   47.705  50.184   1.003  109.008      0.249    0.185   26233.0   
censored[21]   56.009  49.652   9.000  118.069      0.240    0.179   31040.0   
censored[22]   57.072  50.232  10.000  119.500      0.256    0.188   24057.0   
censored[23]   60.519  50.228  13.003  123.027      0.245    0.181   28744.0   
censored[24]   64.915  48.992  18.001  126.386      0.247    0.187   28538.0   
censored[25]   69.497  49.223  22.007  130.892      0.253    0.185   25906.0   
censored[26]   71.621  49.175  25.002  134.745      0.250    0.178   23318.0   
censored[27]   71.762  49.808  25.002  132.754      0.263    0.186   22739.0   
censored[28]   72.257  49.627  25.004  135.370      0.264    0.187   21423.0   
censored[29]   84.694  50.002  38.001  146.637      0.242    0.178   27739.0   
censored[30]   88.196  49.679  41.005  151.409      0.263    0.187   23663.0   
censored[31]   88.136  50.154  41.001  150.518      0.246    0.182   28700.0   
censored[32]   90.900  49.032  44.004  152.906      0.244    0.176   27144.0   
censored[33]   91.784  50.152  45.000  153.728      0.241    0.180   28002.0   
censored[34]   93.384  50.202  46.010  156.206      0.241    0.181   33738.0   
censored[35]   96.053  49.847  49.003  158.275      0.246    0.179   28280.0   
censored[36]   96.766  49.479  50.003  158.160      0.247    0.179   25425.0   
censored[37]  101.033  49.657  54.001  164.237      0.230    0.174   31673.0   
censored[38]  105.991  49.873  59.005  167.903      0.242    0.176   29838.0   
mu_placebo     27.060   5.179  18.417   34.680      0.038    0.027   19211.0   
mu_chemo       46.991  11.796  29.279   64.968      0.077    0.055   24903.0   
mu_diff        19.930  12.849  -0.433   40.056      0.093    0.066   19357.0   
H_prob          0.964   0.186   1.000    1.000      0.001    0.001   25101.0   
H_prob2         0.964   0.186   1.000    1.000      0.001    0.001   25101.0   

              ess_tail  r_hat  
beta0          21245.0    1.0  
beta1          24839.0    1.0  
censored[0]    15029.0    1.0  
censored[1]    17785.0    1.0  
censored[2]    16962.0    1.0  
censored[3]    15897.0    1.0  
censored[4]    17957.0    1.0  
